name: Publish .me

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "public/**"
      - "storage/**"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Setup build cache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/.next/cache
          key: "${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}"

      - run: npm ci
      - run: npm run build

      - name: Deploy
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: ${{ secrets.SOURCE }}
          target: ${{ secrets.TARGET }}
